# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppLovin Mediation Waterfall Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppLovin Mediation Waterfall Demo
  pod 'AppLovinMediationVerveCustomNetworkAdapter', '2.21.2.0'

end
